name: ROS1

on:
  pull_request:
    branches: [ master ]
    paths-ignore: '**.md'
  push:
    branches: [ master ]
    paths-ignore: '**.md'
  repository_dispatch:
    types: [trigger-event]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DISTRO: [
          { "suffix": "gcc", "label": "noetic" },
          { "suffix": "gcc.cuda", "label": "noetic_cuda12.2" },
        ]

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          path: glim_ros1
          submodules: recursive

      - uses: actions/checkout@v2
        with:
          repository: koide3/glim
          token: ${{ secrets.PAT }}
          path: glim
          submodules: recursive
          
      - name: Docker login
        continue-on-error: true
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          tags: koide3/glim_ros1:${{ matrix.DISTRO.label }}
          file: ${{github.workspace}}/glim_ros1/docker/Dockerfile.${{ matrix.DISTRO.suffix }}
          context: .
          push: ${{ (github.event_name == 'push' || github.event_name == 'repository_dispatch') && contains(matrix.DISTRO.suffix, 'gcc') }}
