name: ROS1

on:
  push:
    branches: [ master ]
    paths-ignore: '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          path: glim_ros1
          submodules: recursive

      - uses: actions/checkout@v2
        with:
          repository: koide3/glim
          token: ${{ secrets.GH_PAT }}
          path: glim
          submodules: recursive
          
      - name: Docker login
        continue-on-error: true
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Disable pushing for now to avoid overwriting multiarch images
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          file: ${{github.workspace}}/glim_ros1/docker/noetic/Dockerfile
          context: .
          tags: koide3/glim_ros:noetic
          push: true

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          file: ${{github.workspace}}/glim_ros1/docker/noetic/Dockerfile
          build-args: CMAKE_ARGS="-DBUILD_WITH_CUDA=ON -DBUILD_WITH_CUDA_MULTIARCH=ON"
          context: .
          tags: koide3/glim_ros:noetic_cuda11.2
          push: true
